---
# This is sample a test task environment 
all:
  children:
    suse-test-task:
      children:
        slessrv_ic:
          children:
            dbservers_ic:
              hosts:
                server1ic:
                  ansible_host: 10.1.1.51
            backendservers_ic:
              hosts:
                server2ic:
                  ansible_host: 10.1.1.52
            appservers_ic:
              hosts:
                server3ic:
                  ansible_host: 10.1.1.53
          vars:
            ansible_user: safeadmin
        slessrv:
          children:
            dbservers:
              hosts:
                server1:
                  ansible_host: 192.168.1.79
            backendservers:
              hosts:
                server2:
                  ansible_host: 192.168.1.80
            appservers:
              hosts:
                server3:
                  ansible_host: 192.168.1.81
          vars:
            ansible_user: safeadmin