---
# tasks file for roles/createuser
- name: Create mysql group
  group:
    name: mysql
    state: present
          
- name: Create the '{{ suse_admin_user }}' user
  user:
    name: '{{ suse_admin_user }}'
    shell: /bin/bash
    groups: mysql,users
    comment: '{{ suse_admin_user }} User'
  
- name: Add '{{ suse_admin_user }}' user to sudoers file
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^{{ suse_admin_user }}.*ALL$'
    line: '{{ suse_admin_user }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  
- name: Create '{{ suse_admin_user }}' folders
  file:
    path: "{{ item }}"
    state: directory
    owner: '{{ suse_admin_user }}'
    group: users
    mode: 0700
  with_items:
    - /etc/{{ suse_admin_user }}
    - /opt/suse_test

  
- name: Set security limits for the '{{ suse_admin_user }}' user
  copy:
    src: ../files/limits.conf
    dest: /etc/security/limits.d/99-{{ suse_admin_user }}.conf
    owner: root
    group: root
    mode: 0644

- name: Create '{{ suse_admin_user }}' ssh folder
  file:
    path: /home/{{ suse_admin_user }}/.ssh
    state: directory
    owner: '{{ suse_admin_user }}'
    group: users
    mode: 0700
  
- name: Copy the ssh keys and config for '{{ suse_admin_user }}' user
  copy:
    src: '{{ item.src }}'
    dest: '/home/{{ suse_admin_user }}/.ssh/{{ item.dest }}'
    owner: '{{ suse_admin_user }}'
    group: users
    mode: '{{ item.mode }}'
  with_items:
    - { src: '../files/id_rsa_{{ suse_admin_user }}', dest: 'id_rsa', mode: '0600' }
    - { src: '../files/id_rsa_{{ suse_admin_user }}.pub', dest: 'id_rsa.pub', mode: '0644' }
#    - { src: '../files/ssh_config', dest: 'config', mode: '0644' }
  
- name: Set ssh authorized key for the '{{ suse_admin_user }}'' user
  authorized_key:
    user: '{{ suse_admin_user }}'
    state: present
    key: "{{ lookup('file', '../files/id_rsa_{{ suse_admin_user }}.pub') }}"