---
# -- Provision servers on SLES --
- name:  Copy and change xml file on DB Server SLES15
  hosts: dbservers
  become: false
  vars_files:
    - vars_vault.yml
  roles:
    - role: xmlfilecopy
    


