---
# -- Provision servers on SLES --
- name: Provison all servers SLES15
  hosts: slessrv
  become: true
  gather_facts: true
  vars_files:
    - vars_vault.yml
  roles:
    - role: common
# -- Provision dbservers on SLES --
- name:  Provision DB Server SLES15
  hosts: dbservers
  become: true
  vars_files:
    - vars_vault.yml
  roles:  
    - role: mariadb
#    - role: importBackupToDB
- name:  Copy and change xml file on DB Server SLES15
  hosts: dbservers
  become: false
  vars_files:
    - vars_vault.yml
  roles:
    - role: xmlfilecopy
    


